spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
app.jwt.secret=9a4f2c8d3b52b1c9e8f7g6h5i4j3k2l1m0n9o8p7q6r5s4t3u2v1w0x1y2z3a4b5
spring.jpa.hibernate.ddl-auto=update

cloudinary.cloud-name=dw7vr3ivr
cloudinary.api-key=717735768247214
cloudinary.api-secret=HItCP-1vputIINr4PCxlbTa47c0
cloudinary.upload-folder=ecommerce