spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8
app.jwt.secret=9a4f2c8d3b52b1c9e8f7g6h5i4j3k2l1m0n9o8p7q6r5s4t3u2v1w0x1y2z3a4b5
spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=root
spring.datasource.password=123456
cloudinary.upload-folder=ecommerce

CLOUDINARY_CLOUD_NAME=dfsnuhsff
CLOUDINARY_API_KEY=614452982929243
CLOUDINARY_API_SECRET=fSt43iq63d3_i6hJBn5rY1Z1fwM


spring.ai.google.genai.api-key=AQ.Ab8RN6IZ1fsmR6ZooQNOeNDumkRleN_sHdHvxQF4uu_cdp1NMQ
spring.ai.google.genai.project-id=${GOOGLE_PROJECT_ID:gen-lang-client-0228331347}
spring.ai.google.genai.chat.options.model=${GEMINI_MODEL:gemini-pro}
spring.ai.google.genai.chat.options.temperature=${GEMINI_TEMPERATURE:0.7}