spring.profiles.active=local
spring.application.name=ecommerce

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=${JWT_SECRET:}
app.jwt.expiration=86400000

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
cloudinary.upload-folder=ecommerce

# Sepay payment gateway configuration
sepay.api.url=${SEPAY_API_URL:https://sandbox.sepay.vn/api/v1/payments}


sepay.webhook-url=${SEPAY_WEBHOOK_URL:https://yourdomain.com/api/v1/webhooks/sepay/callback}
sepay.api-key=${SEPAY_API_KEY:}
sepay.webhook-secret=${SEPAY_API_SECRET:}

sepay.bank-account-number=${SEPAY_BANK_ACCOUNT_NUMBER:}
sepay.bank-name=${SEPAY_BANK_NAME:}
sepay.bank-id=${SEPAY_BANK_ID:}

# Gemini API Key 
spring.ai.google.genai.api-key=${GEMINI_API_KEY:}