spring.datasource.url=jdbc:mysql://ecommerce-website-database-ecommerce-website.j.aivencloud.com:15421/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=aiven_password
app.jwt.secret=9a4f2c8d3b52b1c9e8f7g6h5i4j3k2l1m0n9o8p7q6r5s4t3u2v1w0x1y2z3a4b5
spring.jpa.hibernate.ddl-auto=update
spring.ai.google.genai.api-key=AIzaSyBDUC0603n0AQbxjSjaijrlNU_esluOuRA

# Cloudinary Configuration
cloudinary.cloud-name=dvvxjb4ua
cloudinary.api-key=756367459535514
cloudinary.api-secret=XkxfBKiA2qQeYhxn85Ywhp_T8gw
cloudinary.upload-folder=ecommerce